### ISSUE TITLE
__version__ missing

### ISSUE THREAD

**Issue by akhmerov** [conda-forge/kwant-feedstock#12]
Not a very important issue, but currently the resulting package has `__version__ == 'unknown'`.

**Comment by basnijholt** [comment]
I suspect [this](https://gitlab.kwant-project.org/kwant/kwant/blob/master/setup.py#L134) function in `setup.py` somehow doesn't get executed correctly in the building process. This is either a conda or a kwant bug, not of the recipe.

**Comment by basnijholt** [comment]
This is now fixed in version `1.1.2`, `1.1.3`, `1.2.2`, and `1.2.3` :smile:
